#!/usr/bin/env bash
set -euo pipefail

quadlet_dir=/etc/containers/systemd
quadlet_file="$quadlet_dir/gnx-mesh.container"
wsl_conf=/etc/wsl.conf
image="${GNX_LINUX_IMAGE:-docker.io/library/alpine:3.20}"

if ! command -v systemctl >/dev/null 2>&1; then
  echo "systemctl is unavailable in this distribution" >&2
  exit 41
fi

# Quadlet is generated by the system systemd manager, which requires WSL systemd.
if ! grep -Eq '^[[:space:]]*systemd[[:space:]]*=[[:space:]]*true[[:space:]]*$' "$wsl_conf" 2>/dev/null; then
  mkdir -p "$(dirname "$wsl_conf")"
  if [ -f "$wsl_conf" ]; then
    printf '\n[boot]\nsystemd=true\n' >> "$wsl_conf"
  else
    printf '[boot]\nsystemd=true\n' > "$wsl_conf"
  fi
  exit 42
fi

if ! command -v podman >/dev/null 2>&1; then
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends podman
fi

mkdir -p "$quadlet_dir"
cat > "$quadlet_file" <<UNIT
# Managed by GnX Mesh. The systemd generator turns this Quadlet into gnx-mesh.service.
[Unit]
Description=GnX Mesh resilience workload (Podman Quadlet)
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Container]
Image=$image
ContainerName=gnx-mesh
Network=none
ReadOnly=true
Tmpfs=/run/gnx-mesh:rw,noexec,nosuid,nodev,size=1m
Exec=/bin/sh -ec 'while :; do printf "{\\"service\\":\\"gnx-mesh\\",\\"state\\":\\"running\\",\\"updatedAt\\":\\"%s\\"}\\n" "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" > /run/gnx-mesh/heartbeat.json; sleep 30; done'

[Service]
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now gnx-mesh.service
systemctl is-active --quiet gnx-mesh.service
